# Generated by Django 2.2.5 on 2019-10-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('header_text', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('main_text', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'green_planet_article',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_type_code', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')], null=True)),
            ],
            options={
                'db_table': 'green_planet_representation',
            },
        ),
        migrations.CreateModel(
            name='ImageRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('image_file', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'green_planet_image_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='VideoRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('video_url', models.URLField(max_length=1024, null=True)),
            ],
            options={
                'db_table': 'green_planet_video_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='ArticleRepresentation',
            fields=[
                ('article_representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_id', models.PositiveIntegerField(null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to='green_planet_backend.Article')),
                ('representation_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'green_planet_article_representation',
            },
        ),
    ]
