# Generated by Django 2.2.8 on 2020-01-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_nickname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('header_text', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('main_text', models.TextField(blank=True, max_length=65535, null=True)),
                ('original_source_url', models.URLField(blank=True, max_length=65535, null=True)),
                ('state_code', models.IntegerField(choices=[(1, 'Partial'), (2, 'Verified by user')], null=True)),
                ('total_views', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'green_planet_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('article_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'green_planet_article_tag',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_type_code', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')], null=True)),
            ],
            options={
                'db_table': 'green_planet_representation',
            },
        ),
        migrations.CreateModel(
            name='ImageRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('image_file', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'green_planet_image_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='VideoRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('video_url', models.URLField(max_length=1024, null=True)),
            ],
            options={
                'db_table': 'green_planet_video_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='ArticleRepresentation',
            fields=[
                ('article_representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_id', models.PositiveIntegerField(null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_representations', to='green_planet_backend.Article')),
                ('representation_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'green_planet_article_representation',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(to='green_planet_backend.ArticleTag'),
        ),
    ]
