# Generated by Django 2.2.8 on 2020-02-05 14:17

from django.db import migrations, models
import django.db.models.deletion

def populate_article_keywards(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ArticleKeyword = apps.get_model('green_planet_backend', 'ArticleKeyword')
    article_keyword1 = ArticleKeyword.objects.create(article_keyword_id=1, text="Что я могу сделать сам")
    article_keyword1.save()
    article_keyword2 = ArticleKeyword.objects.create(article_keyword_id=2, text="Что может сделать семья")
    article_keyword2.save()
    article_keyword3 = ArticleKeyword.objects.create(article_keyword_id=3, text="Что может сделать человечество")
    article_keyword3.save()
    print("Applying populating article_keywards")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_nickname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('header_text', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('main_text', models.TextField(blank=True, max_length=65535, null=True)),
                ('original_source_url', models.URLField(blank=True, max_length=65535, null=True)),
                ('state_code', models.IntegerField(choices=[(1, 'Partial'), (2, 'Verified by user')], null=True)),
                ('total_views', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'green_planet_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('article_keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'green_planet_article_keyword',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_type_code', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')], null=True)),
            ],
            options={
                'db_table': 'green_planet_representation',
            },
        ),
        migrations.CreateModel(
            name='ImageRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('image_file', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'green_planet_image_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='VideoRepresentation',
            fields=[
                ('representation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='green_planet_backend.Representation')),
                ('video_url', models.URLField(max_length=1024, null=True)),
            ],
            options={
                'db_table': 'green_planet_video_representation',
            },
            bases=('green_planet_backend.representation',),
        ),
        migrations.CreateModel(
            name='ArticleRepresentation',
            fields=[
                ('article_representation_id', models.AutoField(primary_key=True, serialize=False)),
                ('representation_id', models.PositiveIntegerField(null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_representations', to='green_planet_backend.Article')),
                ('representation_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'green_planet_article_representation',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_keywords',
            field=models.ManyToManyField(to='green_planet_backend.ArticleKeyword'),
        ),
        migrations.RunPython(populate_article_keywards),
    ]
