# Generated by Django 2.2.8 on 2020-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_planet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language_code',
            field=models.CharField(choices=[(1, 'Русский'), (2, 'Español'), (3, 'English')], default='ru', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_keywords',
            field=models.ManyToManyField(blank=True, to='green_planet_backend.ArticleKeyword'),
        ),
    ]
