# Generated by Django 2.2.5 on 2019-10-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_planet_backend', '0002_auto_20191012_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerepresentation',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_representations', to='green_planet_backend.Article'),
        ),
    ]
