# Generated by Django 2.2.8 on 2020-10-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_planet_backend', '0002_auto_20200226_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Русский'), ('es', 'Español'), ('en', 'English')], max_length=2),
        ),
    ]
