# Generated by Django 2.2.5 on 2019-10-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_planet_backend', '0003_auto_20191012_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_text',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='articlerepresentation',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_representations', to='green_planet_backend.Article'),
        ),
    ]
