# Generated by Django 2.2.5 on 2019-10-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_planet_backend', '0004_auto_20191027_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_text',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='articlerepresentation',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_representations', to='green_planet_backend.Article'),
        ),
        migrations.AlterField(
            model_name='articlerepresentation',
            name='representation_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
